### ISSUE TITLE
Calendar XML  parse error

### ISSUE THREAD

**Issue by chd999** [glynskyi/ews#1]
Calendar XML  parse error

final service = ExchangeService.withVersion(ExchangeVersion.Exchange2016)
    ..Url = Uri.parse("https://outlook.office365.com/ews/exchange.asmx")
    ..Credentials = WebCredentials(USER_NAME, USER_PASSWORD,null);
final syncFolderId = FolderId.fromWellKnownFolderAndMailbox(WellKnownFolderName.Calendar, Mailbox.fromSmtpAddress("xxxxxx@zzvcsoftware.onmicrosoft.com"));
  ServiceResponseCollection<SyncFolderItemsResponse> r = await service.BuildSyncFolderItemsRequest(syncFolderId, PropertySet.FirstClassProperties, null, 100, 5, SyncFolderItemsScope.NormalItems, null).Execute();

package:ews/Core/EwsUtilities.dart 982:7                              EwsUtilities.Parse
package:ews/PropertyDefinitions/GenericPropertyDefinition.dart 85:25  GenericPropertyDefinition.Parse
package:ews/PropertyDefinitions/TypedPropertyDefinition.dart 117:32   TypedPropertyDefinition.LoadPropertyValueFromXml
package:ews/Core/PropertyBag.dart 545:32                              PropertyBag.LoadFromXml
package:ews/Core/ServiceObjects/ServiceObject.dart 253:22             ServiceObject.LoadFromXmlWithPropertySet
package:ews/Core/Responses/SyncResponse.dart 156:38                   SyncResponse.ReadElementsFromXml
package:ews/Core/Responses/ServiceResponse.dart 116:14                ServiceResponse.LoadFromXml
package:ews/Core/Requests/MultiResponseServiceRequest.dart 71:16      MultiResponseServiceRequest.ParseResponse
package:ews/Core/Requests/ServiceRequestBase.dart 186:17              ServiceRequestBase.ParseResponseWithHeaders
package:ews/Core/Requests/ServiceRequestBase.dart 492:16              ServiceRequestBase.ReadResponseWithHeaders
package:ews/Core/Requests/SimpleServiceRequestBase.dart 194:14        SimpleServiceRequestBase._ReadResponseXml
dart:async                                                            _completeOnAsyncReturn
package:ews/Core/EwsServiceXmlReader.dart                             EwsServiceXmlReader.Create
dart:async                                                            _completeOnAsyncReturn
package:ews/Xml/XmlReader.dart                                        XmlReader.Create

Failed to load "E:\XIANG_MU\appointment_screen-test\appointment_screen-test\test\widget_test.dart": NotImplementedException{message: Parse<LegacyFreeBusyStatus>(Busy)}

**Comment by featzima** [comment]
Thanks for feedback. I'll add the parsing of 'Busy' property on March 17.

**Comment by glynskyi** [comment]
fixed in v1.0.10
