### ISSUE TITLE
Strategy for dealing with password changes

### ISSUE THREAD

**Issue by thumbert** [glynskyi/ews#10]
Hi,

What an amazing package.  Thank you very much for making it available to the community.

I am exploring using the package for sending emails from automated jobs.  My organization requires a new password every month.  Is there a way for the Credentials to use Active Directory to get the current password?  That would save me the trouble to hash and store my password every time after it gets changed. 

Thanks,
Tony

**Comment by featzima** [comment]
@thumbert If I understand correctly the .NET version of EWS library uses special classes for Active Directory that are available on .NET platform. Because Dart SDK doesn't have such classes I'm not sure that your desire is feasible.

**Comment by thumbert** [comment]
Understood.  Thank you.
