### ISSUE TITLE
How to add Attachments? 

### ISSUE THREAD

**Issue by thumbert** [glynskyi/ews#11]
Hi,

I'm trying to add an attachment to a message and I can't make it work.  

```dart
var file = File('C:\\README.txt');
final message = EmailMessage(service)
    ..Subject = 'test message'
    ..Body = MessageBody.withText('line1\nline2\n\nBye', BodyType.Text)
    ..ToRecipients.Add(EmailAddress(smtpAddress: to));
message.Attachments.AddFileAttachmentWithContent('filename.txt', file.readAsBytesSync());
await message.Save();

message.Send();
```
I get no errors, but no message is sent (nor it is saved in the Drafts folder).  If I try to use  ```await message.SendAndSaveCopy();``` I get an error message. 

I looked in the test directory but couldn't find anything that can help.  Maybe it's also worth adding as an example to the documentation page as it is a pretty common task.  

Thank you very much,
Tony

**Comment by glynskyi** [comment]
It looks you need to get an email message again before sending it. I changed your sample a little bit and added it to the tests https://github.com/glynskyi/ews/blob/master/test/test_email_sending.dart
