### ISSUE TITLE
Value not in range: -1

### ISSUE THREAD

**Issue by chd999** [glynskyi/ews#2]
final folderId = FolderId.fromWellKnownFolderAndMailbox(WellKnownFolderName.Calendar, Mailbox.fromSmtpAddress("xxxxx@xxx.onmicrosoft.com"));
DateTime start = DateTime.parse("2020-03-18T16:00:00Z");
  DateTime end = DateTime.parse("2020-03-19T16:00:00Z");
  FindItemsResults<Item> fi =await service.FindItemsWithFolderIdAndView(folderId,CalendarView(start,end));

dart:core                                                              _StringBase.substring
package:ews/Core/EwsUtilities.dart 2818:38                             EwsUtilities.XSDurationToTimeSpan
package:ews/PropertyDefinitions/TimeSpanPropertyDefinition.dart 54:25  TimeSpanPropertyDefinition.Parse
package:ews/PropertyDefinitions/TypedPropertyDefinition.dart 117:32    TypedPropertyDefinition.LoadPropertyValueFromXml
package:ews/Core/PropertyBag.dart 545:32                               PropertyBag.LoadFromXml
package:ews/Core/ServiceObjects/ServiceObject.dart 253:22              ServiceObject.LoadFromXmlWithPropertySet
package:ews/Core/Responses/FindItemResponse.dart 178:18                FindItemResponse._InternalReadItemsFromXml
package:ews/Core/Responses/FindItemResponse.dart 92:7                  FindItemResponse.ReadElementsFromXml
package:ews/Core/Responses/ServiceResponse.dart 116:14                 ServiceResponse.LoadFromXml
package:ews/Core/Requests/MultiResponseServiceRequest.dart 71:16       MultiResponseServiceRequest.ParseResponse
package:ews/Core/Requests/ServiceRequestBase.dart 186:17               ServiceRequestBase.ParseResponseWithHeaders
package:ews/Core/Requests/ServiceRequestBase.dart 492:16               ServiceRequestBase.ReadResponseWithHeaders
package:ews/Core/Requests/SimpleServiceRequestBase.dart 194:14         SimpleServiceRequestBase._ReadResponseXml
dart:async                                                             _completeOnAsyncReturn
package:ews/Core/EwsServiceXmlReader.dart                              EwsServiceXmlReader.Create
dart:async                                                             _completeOnAsyncReturn
package:ews/Xml/XmlReader.dart                                         XmlReader.Create

Failed to load "E:\XIANG_MU\appointment_screen-test\appointment_screen-test\test\widget_test.dart": Value not in range: -1

**Comment by chd999** [comment]
EwsUtilities.dart  2814

xsTimeDuration ="21M42S"
m = PATTERN_SECONDS.firstMatch(xsTimeDuration);

    int seconds = 0;
    if (m != null) {
      seconds = int.parse(m.group(0).substring(0, m.group(0).indexOf(".")));
    }

@glynskyi

**Comment by glynskyi** [comment]
fixed in v1.0.12
