### ISSUE TITLE
Reason behind putting copyright on every code file

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [glynskyi/ews#7]
Hello, I've been looking at the code and it looks like you have copyright notice written in every file. What is reason for having it when you already have lincense file? 

Also I would like to contribute to repo by improving static analysis of the code for now. Let me know if you are okay with it. Thanks

**Comment by featzima** [comment]
The `ews` library is partially ported from the Microsoft source code. It's very important to save the original code style until all the code is migrated.
