### ISSUE TITLE
appointment.Update  NotImplementedException

### ISSUE THREAD

**Issue by chd999** [glynskyi/ews#8]
ItemId id = ItemId.withUniqueId(“xxxxxxxxxx”）；
Appointment appointment = await Appointment.BindWithItemId(service, id);
appointment.SetSubject("subject");
Item i = await appointment.Update(ConflictResolutionMode.AlwaysOverwrite,true);

package:ews/Core/EwsServiceXmlWriter.dart 124:9           EwsServiceXmlWriter.TryConvertObjectToString
package:ews/Core/EwsServiceXmlWriter.dart 251:14          EwsServiceXmlWriter.WriteAttributeValue
package:ews/Core/Requests/UpdateItemRequest.dart 196:14   UpdateItemRequest.WriteAttributesToXml
package:ews/Core/Requests/ServiceRequestBase.dart 210:10  ServiceRequestBase.WriteBodyToXml
package:ews/Core/Requests/ServiceRequestBase.dart 380:10  ServiceRequestBase.WriteToXml
package:ews/Core/Requests/ServiceRequestBase.dart 413:10  ServiceRequestBase._EmitRequest

NotImplementedException{message: !!! TryConvertObjectToString SendInvitationsOrCancellationsMode.SendToAllAndSaveCopy of type SendInvitationsOrCancellationsMode}

**Comment by glynskyi** [comment]
Resolved in [v1.1.2](https://pub.dev/packages/ews/versions/1.1.2 )
